blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/6jt8/weather-extension/security/advisories/new
    about: Report a security vulnerability